name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      sdk_name:
        description: SDK to release (sentry-raven, sentry-rails, sentry-ruby, sentry-sidekiq, sentry-delayed_job)
        required: true
      version:
        description: Version to release
        required: true
      force:
        description: Force a release even when there are release-blockers (optional)
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    name: "Release a new version"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_RELEASE_PAT }}
          fetch-depth: 0
      - name: Prepare release
        uses: getsentry/action-prepare-release@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        with:
          path: ${{ github.event.inputs.sdk_name }}
          version: ${{ github.event.inputs.version }}
          force: ${{ github.event.inputs.force }}
